name: flutter_base_riverpod
description: Flutter Base Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_multi_formatter: ^2.12.1
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  get_it: ^7.6.4
  go_router: ^12.1.3
  image_picker: ^1.0.4
  jiffy: ^6.2.1
  json_serializable: ^6.7.1
  lottie: ^2.7.0
  onesignal_flutter: ^5.0.4
  package_info_plus: ^5.0.1
  page_transition: ^2.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  sentry_flutter: ^7.13.2
  share_plus: ^7.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - .env.dev
    - .env.prod
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
